name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install
        run: pip install tox

      - name: lint check
        run: tox -e lint-check

      - name: format and commit if needed
        if: failure()
        run: |
          tox -e lint
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: Format with black and isort"
          git push
  test-linux:
    name: test python ${{ matrix.python-version }} on linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11.0-rc.2']
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Run test
        run: tox -e py$(echo ${{ matrix.python-version }} | sed 's/\.0-rc\.2//' | sed 's/\.//' )
